### ISSUE TITLE
element-ui表格在Safari下样式错乱

### ISSUE THREAD

**Issue by Bobjoy** [Bobjoy/bobjoy.github.io#34]
## 添加样式

```css
body .el-table th.gutter {
  display: table-cell !important;
}

body .el-table colgroup.gutter {
  display: table-cell !important;
}

table {
  width: 100% !important;
}

.el-table__body {
  // 使表格兼容safari，不错位
  width: 100%;
  table-layout: fixed !important;
}
```
